### ISSUE TITLE
Users can circumvent interstitials

### ISSUE THREAD

**Issue by sekodev** [coronalabs/com.coronalabs-plugin.admob#2]
It seems that users are able to circumvent interstitials by sending the app to background and bringing it back.

[Related forum topic](https://forums.solar2d.com/t/users-able-to-circumvent-interstitials/352114) and [possible solution](https://forums.solar2d.com/t/users-able-to-circumvent-interstitials/352114/5).

**Comment by scottrules44** [comment]
I just tried this and this issues seems to have been patch
