### ISSUE TITLE
Admob Banner Crashes on iOS

### ISSUE THREAD

**Issue by yosus** [coronalabs/com.coronalabs-plugin.admob#3]
Hi,

Only on iOS. No issue on Android. 

When showing Admob banner 
`admob.show( "banner", { y = 50 } )`

if the position is set as such `y=50 (or any number)` the app will crash. It will work if `y=top (or other strings)`

Issue has been posted here : https://forums.solar2d.com/t/admob-on-ios-crashed-on-banner/352294

**Comment by scottrules44** [comment]
This appears to have been fixed in my testing
