### ISSUE TITLE
Reward ads on android open without timer and closing button

### ISSUE THREAD

**Issue by koyan** [coronalabs/com.coronalabs-plugin.admob#4]
[Related forum topic](https://forums.solar2d.com/t/admob-rewarded-video-fixed/351876/5) 
When an admob rewardAd opens in android, most of the times it does not have the timer (when it should close) and the "x" button (when it completes). 
This leaves the player with nothing to do at this stage.

**Comment by joelutting** [comment]
it has been this way for a while - I've given up using reward ads altogether (which is so annoying).

**Comment by appfamily** [comment]
I've been troubleshooting this in https://github.com/coronalabs/corona/issues/202

**Comment by Shchvova** [comment]
I'm happy to say taht this seems to be fixed!
