### ISSUE TITLE
Latest Admob version only show banner once

### ISSUE THREAD

**Issue by hosaysg** [coronalabs/com.coronalabs-plugin.admob#8]
Platform: iOS

Admob banner only gets loaded once. When I tried to load it again for a new banner, it never gets loaded.

Using admob v23 solves this issue.

["plugin.admob"] =
	{
	publisherId = "com.coronalabs",
	version = "v23",
	},

However, v23 will cause build issue (duplicate symbols) when using firebase notifications for iOS.

**Comment by scottrules44** [comment]
Can you share your code with how you are load your banners? I just tried reloading, cannot repoduce?

https://github.com/coronalabs/com.coronalabs-plugin.admob/assets/7820808/3a7e4323-b255-41bb-9944-af6c05c209c2

**Comment by hosaysg** [comment]
```
local function loadAds()
    print("load admob banner")
    if device.isApple then
        admob.load( "banner", { adUnitId= adUnitID_iOS_banner} )
    else
        admob.load( "banner", { adUnitId= adUnitID_android_banner} )
    end
end

local function admobListener(event)
    if ( event.isError ) then
        print("admob banner error")
        print(event.response)
    elseif ( event.phase == "init" ) then  -- Successful initialization
        M.isInitialized = true
        loadAds()
    elseif (event.phase == "loaded") then
        print("show admob banner")
        admob.show("banner", {y = display.contentHeight - admob.height() - bottomInset- safearea})
    end
end

function M:init()
    if device.isApple then
        admob.init(admobListener, {testMode=false} )
    else
        admob.init(admobListener, {testMode=false} )
    end
end

function M:show()
    if self.isInitialized then
        admob.show("banner", {y = display.contentHeight - admob.height() - bottomInset- safearea})
        loadAds()
    else
        self:init() 
    end
end

function M:hide()
    print("hide admob banner")
    if admob.isLoaded("banner") then
        admob.hide()
    end
end
```

**Comment by scottrules44** [comment]
My guess is you expect print("show admob banner") to be fired when event.phase == "loaded" is called, but if a banner is already loaded it is "refreshed" not "loaded". 

https://docs.coronalabs.com/plugin/admob/event/adsRequest/phase.html

v23 originally destroyed the banner instead of reloading which is not the best practice
